services:
  llm-service:
    container_name: cvhub-llm

    build:
      context: .
      dockerfile: Dockerfile
      args:
        VLLM_VERSION: ${VLLM_VERSION:-latest}

    image: cvhub-llm:${VLLM_VERSION:-latest}

    env_file:
      - .env

    ports:
      - "${LLM_PORT:-8000}:${LLM_PORT:-8000}"

    volumes:
      - ../models:/models:ro

    ipc: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

    restart: unless-stopped